### ISSUE TITLE
Crear #US10, #TK 10  y la tabla de Sprint 00 en el Documento IEEE830 y el Mapa de Sitio 

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#14]
Se solicita crear la Historia de Usuario y la tarea asignadas en el Documento IEEE830, como así también crear el Mapa de Sitio y la carga del sprint 0

**Comment by ChRi5714n** [comment]
![Image](https://user-images.githubusercontent.com/107540610/193611341-61d7db0c-26ca-49b0-9293-2caa1262cd45.png)

**Comment by ChRi5714n** [comment]
Historia de Usuario y la tarea asignadas en el Documento IEEE830 **TERMINADO**

**Comment by ChRi5714n** [comment]
Carga del sprint 0 - **TERMINADO**
