### ISSUE TITLE
Pensar nombres para la empresa de desarrollo web.

### ISSUE THREAD

**Issue by ChRi5714n** [hernan04/fullstack#21]
Realicemos una **_lluvia de ideas_** para el nombre de nuestra empresa de **desarrollo web**

**Comment by nadgis** [comment]
Paso algunos en ingles y en español:  Our tech club,  The fighters technologi, Gladiadores tecnologicos, Union01010101,  Los ocho bit , Demonios de interfaz.

**Comment by MaxiCantarino** [comment]
404 forbidden, level up , Virtual tech,top tech,innova tech, Virtual Terra

**Comment by stefaniajara** [comment]
Level Up suena lindo

**Comment by ChRi5714n** [comment]
me fijé en nic.ar y ya esta registrado "Level Up", en cambio "ochobit.com.ar" y "ochobit.ar" están disponibles.

Me gusta como queda escrito así: **"OCHOBIT"**
Apoyo esa propuesta!

**Comment by Monimo1** [comment]
Bit web. DW Soluciones. Me fascino 8bit!!!

**Comment by stefaniajara** [comment]
Genial, me gusta OCHOBIT. También apoyo esa propuesta.

**Comment by nadgis** [comment]
Yo también apoyo a OCHOBIT!!

**Comment by matiasmassuh** [comment]
8 bit me gusta.

**Comment by hernan04** [comment]
Big Ideas, Ideamantes, Creator

**Comment by matiasmassuh** [comment]
Desarrollos Suro
Pridea
