### ISSUE TITLE
Maquetado de página de acuerdo al boceto

### ISSUE THREAD

**Issue by ChRi5714n** [hernan04/fullstack#24]

**Comment by stefaniajara** [comment]
buenas buenas, ya he avanzado en el index, las secciones que contiene la página con sus links funcionales y los estilos en css con los respectivos responsives.

**Comment by stefaniajara** [comment]
Queda cargar información en cada sección, pulir algunos detalles y, una vez elegido el nombre de la empresa, ponerlo en el footer, en el copyright.
