### ISSUE TITLE
Escribir contenido de la página "Quienes Somos"

### ISSUE THREAD

**Issue by ChRi5714n** [hernan04/fullstack#27]

**Comment by ChRi5714n** [comment]
**Quienes somos**

Los profundos cambios y transformaciones económicos observados a nivel mundial obligan a buscar nuevas fuentes de recursos y desarrollo, encontrando en el Arte y la Cultura una alternativa factible. En vistas a este panorama se han desarrollado en diferentes países exitosas experiencias de fomento de las Industrias de Base Cultural (IC), logrando importantes repercusiones no sólo en materia social sino también económica. 

La alta productividad de las actividades culturales y sus innegables impactos en diferentes ámbitos de la economía, como por ejemplo el turismo, son una clara manifestación de la interconexión cultura-economía.

**M.A.S.C. (Mercado de Arte y Servicios Culturales)** es un proyecto de base tecnológica que busca potenciar la difusión y comercialización de productos y servicios relacionados al arte y la cultura, apoyando a los emprendedores culturales a nivel nacional. 

**MISIÓN**

En **M.A.S.C** tenemos la misión de promover la industria cultural del país, otorgándoles a los artistas y emprendedores culturales en general, diferentes herramientas para la comercialización o difusión de sus obras o servicios.

**VISIÓN**

En **M.A.S.C** aspiramos a ser la plataforma digital con e-commerce más importante del país en materia de Industrias Creativas.

**Comment by ChRi5714n** [comment]
Completado

**Comment by stefaniajara** [comment]
Gracias Christian. Ahora lo completo en la página.

**Comment by stefaniajara** [comment]
Listo, ya quedó cargado en la página!
