### ISSUE TITLE
RETROSPECTIVE - SPRINT 1

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#30]
Grupo, aprovechando el momento del _Sprint Planning_, debemos realizar la _Restrospective_ del Sprint 1.

Recuerden que el objetivo es reflexionar sobre cómo nos hemos manejado para poder mejorar en el Sprint 2.

_**Puntos a analizar:**_
1. Qué salió bien
2. Qué podemos mejorar
3. Plan de acción

### **Les invito a que apunten lo que piensan al respecto para que en la reunión cada uno lo exponga y así podemos debatirlo.**

**Comment by matiasmassuh** [comment]
1. Pudimos mantener el grupo. Aunque perdimos dos integrantes.
2. Tendríamos que nivelar el nivel de conocimiento de los integrantes. Al menos intentarlo.
3. Tratar de hacer la actividad en conjunto, para que todos los integrantes vean el paso a paso, en cada faceta.

**Comment by stefaniajara** [comment]
> 1. Pudimos mantener el grupo. Aunque perdimos dos integrantes.
> 2. Tendríamos que nivelar el nivel de conocimiento de los integrantes. Al menos intentarlo.
> 3. Tratar de hacer la actividad en conjunto, para que todos los integrantes vean el paso a paso, en cada faceta.

Anotado.
Me parece que para lograr esas cuestiones es sumamente necesario que los integrantes se comprometieran y asumieran las responsabilidades que les corresponden, tanto para conectarse en las reuniones, para participar en las actividades, en las tareas que hay que realizar y así poder nivelar los conocimientos. 
Si no se participa ni se suman a realizar las tareas, no se aprende ni se puede integrar.
Gracias

**Comment by ChRi5714n** [comment]
Estoy de acuerdo con el comentario de Matias y con lo hablado en la reunión del 19/10.
