### ISSUE TITLE
Hosting Remoto

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#31]
Averiguar opciones y precios de _hosting remotos_ para el Sitio Institucional en WordPress.

**Realizar los comentarios en este mismo issue.**

**Comment by matiasmassuh** [comment]
Encontré este por $1044 y que tiene promociones temporales.
https://www.wnpower.com/web-hosting/

**Comment by MaxiCantarino** [comment]
Hola a todos ,aca subo las mejores opciones que estuve viendo para wordpress

https://hostrentable.com/

Hostinger

Por el precio y funciones optaria por hostrentable,sigo averiguando mientras tanto 



Gratuitos
https://aws.amazon.com/es/free/webapps/?trk=4ca1ce73-7fd6-4c93-beb3-19360f50c696&sc_channel=ps&s_kwcid=AL!4422!3!590562423494!p!!g!!hosting%20web&ef_id=Cj0KCQjwhsmaBhCvARIsAIbEbH62LiudARMP9fMTu5dMDZolo6gdT0rLYYTM0345TmXn2TxeD4T5WDkaAjkWEALw_wcB:G:s&s_kwcid=AL!4422!3!590562423494!p!!g!!hosting%20web


Google cloud

Netlify

**Comment by stefaniajara** [comment]
Genial Maxi, hoy en la reunión lo vamos charlando
