### ISSUE TITLE
Funcionalidad con JavaScript

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#32]
Funcionalidad con _JavaScript en formularios_. Recordar de informar si pueden realizarlos o no, así se trabaja de manera colaborativa con todo el team.

**Realizar los comentarios en este mismo issue.**

**Comment by ChRi5714n** [comment]
Recibido!

**Comment by nadgis** [comment]
Comenzamos a interiorizarnos en el tema.
