### ISSUE TITLE
Script BD y consultas

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#33]
Script en MySQL y las consultas. Recordar de informar si pueden realizarlos o no, así se trabaja de manera colaborativa con todo el team.

Realizar los comentarios en este mismo issue.

**Comment by Marialer27** [comment]
Buenas tardes, si puedo realizar el script. Saludos!

**Comment by matiasmassuh** [comment]
> Buenas tardes, si puedo realizar el script. Saludos!

En qué horario soles hacerlo?
