### ISSUE TITLE
#US11: Como usuario quiero tener una seccion donde pueda hacer mis preguntas frecuentes

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#42]

**Comment by stefaniajara** [comment]
Al comienzo del Sprint 00 se debatió y se acordó no llevar a cabo un blog dentro de la página. Puede proponerse un nuevo debate en la reunión de mañana.

**Comment by stefaniajara** [comment]
#US1: Como usuario quiero tener un botón de Preguntas Frecuentes para visualizar si mis dudas o inquietudes ya están aclaradas.

#TK12: Crear un botón de Preguntas Frecuentes para que el usuario pueda acceder a él y solventar sus dudas.

**Comment by MaxiCantarino** [comment]
La seccion esta creada!!! faltaria el boton!!
