### ISSUE TITLE
#US13: Garantizar la disponibilidad continua del sistema, contando con una contingencia, generación de alarmas en caso de que se produzca una posible falla en cualquiera de sus componentes.

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#44]

**Comment by stefaniajara** [comment]
Bien, entiendo que esta US estaría apuntando más a un RNF, mientras que las otras a los RF.

#US13: Como usuario quiero que el sistema garantice su funcionamiento las 24 horas de los 7 días de la semana para poder hacer uso de la página web cada vez que quiera sin ningún impedimento.

#TK13: Garantizar la disponibilidad continua del sistema, contando con una contingencia, generación de alarmas en caso de que se produzca una posible falla en cualquiera de sus componentes.
