### ISSUE TITLE
#US14: El sistema debe permitir el ingreso de nuevos artistas, además podrá modificar y eliminar estos registros personales y cargar nuevo material 

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#45]

**Comment by stefaniajara** [comment]
Maxi, lo hablamos en la reunión del otro día, había que reescribir las US en la nomenclatura correcta.
Además, esta US la debatimos para encontrar el sentido en el que te referías y no la cambiaste.

#US14: Como usuario quiero que el sistema permita modificar los artistas publicados.

#TK13: Garantizar la labor de un administrador del sistema que se encargue de las modificaciones respecto de los artistas publicados.
