### ISSUE TITLE
#US15: La aplicación web mostrará los artistas pedidos, recibidos, disponibles y en stock

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#46]

**Comment by stefaniajara** [comment]
Bien, podría ir así:

#US15: Como usuario quiero que la página web me muestre los servicios/obras que he pedido, recibido, y los que se encuentren disponibles para poder ver de manera certera lo que se encuentra en stock y lo adquirido.

#TK15: Crear una sección dentro de las subcategorías de artistas que muestre el stock y agregar en la sección "Usuario" lo que el usuario ha pedido y recibido en un historial.

**Comment by stefaniajara** [comment]
Bien, podría ir así:

#US15: Como usuario quiero que la página web me muestre los servicios/obras que he pedido, recibido, y los que se encuentren disponibles para poder ver de manera certera lo que se encuentra en stock y lo adquirido.

#TK15: Crear una sección dentro de las subcategorías de artistas que muestre el stock y agregar en la sección "Usuario" lo que el usuario ha pedido y recibido en un historial.

**Comment by stefaniajara** [comment]
Bien, podría ir así:

#US15: Como usuario quiero que la página web me muestre los servicios/obras que he pedido, recibido, y los que se encuentren disponibles para poder ver de manera certera lo que se encuentra en stock y lo adquirido.

#TK15: Crear una sección dentro de las subcategorías de artistas que muestre el stock y agregar en la sección "Usuario" lo que el usuario ha pedido y recibido en un historial.
