### ISSUE TITLE
#US19:El sistema deberá registrar las horas de entrada y salida de los usuarios para el control de trafico y cual de las secciones deberan mejorarse o retirar para mejorar

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#50]

**Comment by stefaniajara** [comment]
#US19: Como usuario quiero que el sistema lleve un registro de los horarios de entrada y salida de los visitantes de la página para tener un control de tráfico y poder encontrar qué hay que mejorar.

#TK19: Generar un registro de horarios para un control estadístico por secciones.
