### ISSUE TITLE
#US20:El sistema deberá poder generar una Gift card automática y ser enviada via correo electrónico

### ISSUE THREAD

**Issue by MaxiCantarino** [hernan04/fullstack#51]

**Comment by stefaniajara** [comment]
En este caso se puede reescribir algo así...

#US20: Como usuario quiero que el sistema me pueda otorgar Gift Cards para poder adquirirlas cuando desee.

#TK20: Crear una sección "Gift Cards" para que el usuario pueda adquirir una y le llegue vía correo electrónico.
