### ISSUE TITLE
OCHOBIT WordPress: completar secciones

### ISSUE THREAD

**Issue by stefaniajara** [hernan04/fullstack#54]
Completar7armar cada una de las secciones que se encuentran en el Sitio Institucional de la empresa OCHOBIT.

Recordar subir los CVs de cada uno

**Comment by stefaniajara** [comment]
Ya está cargado mi CV.
Hice algunas modificaciones en el inicio :)

**Comment by MaxiCantarino** [comment]
ya esta cargado mi CV.

**Comment by MaxiCantarino** [comment]
Se diseño y se agrego todas las secciones de tecnologia y se cargaron las descripciones tecnologia en cada seccion .

**Comment by nadgis** [comment]
Ya esta cargado mi CV y se completó post de Formulario en JS.

**Comment by stefaniajara** [comment]
- Ya están cargadas mis entradas al post.
- Rediseñé páginas para lograr una armonía en todo el sitio
- Agregué en el Inicio un Slide que muestra en una de sus hojas el proyecto de FullStack
- Cambié el diseño que muestra a los integrantes del equipo, para que sea más dinámico y redirija a los CV de cada uno
- Agregué en el menú un botón de Inicio y de Presentación, para cumplir con lo solicitado en el documento: https://docs.google.com/document/d/1oWo5-h16jsunkRrOdoeIfQS_TXcD0UZbZHyWB7kiGkA/edit

**Comment by Marialer27** [comment]
Ya está cargado mi CV y cargadas mis entradas al post.
